---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- value: Rojo
  checked: false
- value: Verde
  checked: true
- value: colorcito
  checked: false
- value: 'True'
  checked: false
- value: 'False'
  checked: false
